image: openjdk
pages:
  script:
    #- cd ..
    - mkdir public
    - javadoc -sourcepath ./src/* -classpath "./lib/*" -d public -private -doctitle "BehaviorMate" -windowtitle "BehaviorMate" -author -bottom "Â© Copyright 2021, Losonczy Lab, Jack Bowler" || NO_CONTAINER=1
    # WORKS: - javadoc -sourcepath ./src/* -classpath "./lib/*" -d public -private -doctitle "BehaviorMate" || NO_CONTAINER=1
    #- javadoc --help -doctitle "<p>$PACKAGE</p>" -windowtitle "$PACKAGE"
    #javadoc -classpath "$PACKAGE/lib/*" -sourcepath "$PACKAGE/src/*" -subpackages $PACKAGE -d public -private  || NO_CONTAINER=1
  artifacts:
    paths:
      - public